app = "deliverydist-web"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "3000"
  NEXT_PUBLIC_API_URL = "https://deliverydist-api.fly.dev"
  
[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"