version: '3.8'

services:
  backend:
    build: 
      context: .
      target: backend-build
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/backend/data
    command: >
      sh -c "cd backend && 
             poetry run alembic upgrade head &&
             poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"

  frontend:
    build: 
      context: .
      target: frontend-build
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend