version: '3.8'

services:
  backend:
    build: 
      context: .
      target: backend-build
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: .
      target: frontend-build
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend