app = 'deliverydist'
primary_region = 'gru'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'

[[mounts]]
  source = 'data'
  destination = '/data'

# Configuration for the FastAPI backend
[services.backend]
  internal_port = 8000
  protocol = "tcp"
  force_https = true

  [[services.backend.ports]]
    port = 8000
    handlers = ["http"]

  [[services.backend.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/api/v1/health"
    protocol = "http"
    port = 8000

# Configuration for the Next.js frontend
[services.frontend]
  internal_port = 3000
  protocol = "tcp"
  force_https = true

  [[services.frontend.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.frontend.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1