app = "deliverydist-api"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8000
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = "30s"
    timeout = "10s"
    grace_period = "20s"
    method = "GET"
    path = "/api/v1/health"
    protocol = "http"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"